# Generated by Django 4.2 on 2024-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_solicitudarriendo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
